#!/bin/bash


allow_push=$( python3 -m main get allow-push )
if $allow_push; then
    
  python3 -m main set allow-push false
  
  git add .
  git commit -m "autocommit"
  git push https://alanmatzumiya:$( head $HOME/secret )@github.com/CircuitalMinds/static.git
  
fi

